name: Playporter
options:
  bundleIdPrefix: com.itinnove
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    ENABLE_HARDENED_RUNTIME: YES
targets:
  Playporter:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.itinnove.playporter
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Playporter
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.developer-tools"
        INFOPLIST_KEY_NSHumanReadableCopyright: "© 2026 IT INNOVE"
        MARKETING_VERSION: "0.1.0"
